sudo: false
os: linux
dist: bionic
language: go
go:
- 1.13.x

env:
  global:
  - LANG=C
  - LC_ALL=C
  - OUTPUT="shikigrid"
  - VERSION=$(echo ${TRAVIS_BRANCH} | sed "s/\//_/g")

cache:
  apt: true
addons:
  apt:
    packages:
    - wget
    - p7zip-full
    - libpcap-dev
    update: true

cross: &cross
  before_install:
  - wget --show-progress -qcO "qemu.deb" "https://debian.grena.ge/debian/pool/main/q/qemu/qemu-user-static_4.1-1+b4_amd64.deb"
  - sudo dpkg -i "qemu.deb"
  install:
  - sudo builder/arm_builder.sh shikigrid make -e TARGET="${OUTPUT}"

normal: &normal
  install:
  - make -e TARGET="${OUTPUT}"

end: &end
  after_success:
  - sudo mv "build/${OUTPUT}" "${OUTPUT}"
  - file "${OUTPUT}"
  - openssl dgst -sha256 "${OUTPUT}" | tee "${OUTPUT}_${TARGET_OS}_${TARGET_ARCH}_${VERSION}.sha256"
  - 7z a "${OUTPUT}_${TARGET_OS}_${TARGET_ARCH}_${VERSION}.zip" "${OUTPUT}" "${OUTPUT}_${TARGET_OS}_${TARGET_ARCH}_${VERSION}.sha256"

matrix:
  include:
  - name: Linux - amd64
    if: tag IS present
    arch: amd64
    env:
    - TARGET_OS=linux
    - TARGET_ARCH=amd64
    <<: *normal
    <<: *end
  - name: Linux - aarch64
    if: tag IS present
    arch: arm64
    env:
    - TARGET_OS=linux
    - TARGET_ARCH=aarch64
    <<: *normal
    <<: *end
  - name: Linux - armhf
    if: tag IS present
    arch: amd64
    language: minimal
    env:
    - TARGET_OS=linux
    - TARGET_ARCH=armhf
    <<: *cross
    <<: *end
    # Tests
    #  - name: Linux - tests
    #    if: tag IS blank
    #    os: linux
    #    arch: amd64
    #    install:
    #      - make deps
    #    script:
    #      - make test
    #    after_success:
    #      - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: ljBVe/wVAtOPwCWJPlJ7D1hWGfm6GtHOLgq3wmP4jw/9a2RYV41xJ7g+4R1mm9R8waqtTm9QPDHIKFuN3N9cNs83ZY/fkSJ2WwU3IDV1ZvKPAuucrMSsyOGc08poXj6mmUDs/9LRb100qG81Y5dD+WB6Ep6vWOT7aOi9QNp/WWQ3IDYp5QJIocRHcJhGFH8JO1699mpdNgaukmPHIYK6uVu15TCkYOrvNTD0OTpthN6hIwCBwQ0agFNBbqmwyYsAdUZsjdU7QVOCnPUeXWqoZwq3klFKymsf8f4xra7ou5hsBkL+GFESiGGy0TdU7ZTZjPRKgkpIWtHOURq3WSVtYvCTnKI8h+HdBbKlQeO5g611gUw3CEU5HZxKlG18JTSD5TJNuEAFBVA7X385cVnWbgCLIwLiCDzjKPeVJvyDxyKC1CCtmfYZtanyn18qz/VRtMWrLFRcr5jNrQcloiuJbQzteoxtvbt5c0nM7b1b/AZ4zzGH75MLADxbHw2CThN4R+dxx3lqD0YM3fxbWiWCgZlbrc7GNRq1ilhX0YEDBOVfcdJxYARwrzovrO8bMFGerur4C7HzkpVgE6jfQiZJdXU/5javkLnww6xjDC/jfiMJ7i4OqZ2sgISSVL8Fq4LMqaAumdSHZK/GoJ97PTWUE9sBD7tIGSzHReA8DhpweFI=
  skip_cleanup: true
  file_glob: true
  file:
    - shikigrid_*.zip
    - shikigrid_*.sha256
  on:
    tags: true
    repo: evilsocket/shikigrid
  branches:
    only:
    - "/^v[0-9]+\\.[0-9]+\\.[0-9]+[A-Za-z0-9]+?$/"
