version: '3'
services:
  app:
    container_name: shikigrid_api
    build: .
    ports:
      - 8666:8666
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - shikigrid-mysql
    networks:
      - shikigrid

  shikigrid-mysql:
    image: mysql:5.7
    container_name: shikigrid_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - shikigrid

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shikigrid_phpmyadmin
    depends_on:
      - shikigrid-mysql
    environment:
      - PMA_HOST=shikigrid-mysql
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - shikigrid

volumes:
  api:
  database_mysql:

networks:
  shikigrid:
    driver: bridge
